# Generated by Django 4.2.1 on 2023-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="income_id",
            field=models.CharField(
                default="#cd7ad500-e399-4dd3-96e4-6c9b48487eac",
                max_length=255,
                verbose_name="Mahsulot id raqami",
            ),
        ),
    ]
